### ISSUE TITLE
Crash and hang when trying to generate

### ISSUE THREAD

**Issue by rappen** [albanian-xrm/Early-Bound#21]
See: https://www.screencast.com/t/a6CwLq6vb

I'm assuming this is because I haven't done _Get CoreTools_ but error handling must be improved.

**Comment by BetimBeja** [comment]
That was fast. And you are assuming right... The generate button should not be active if CoreTools have not been downloaded and that will be fixed ASAP.

Thank you Jonas.

Best regards,
Betim.

**Comment by BetimBeja** [comment]
I did some improvements, although I would leave the issue open as there is more work to have a better error handling.

Betim.

**Comment by BetimBeja** [comment]
PR #27 by @MirvinGuleksi should improve the error messages handling so I am closing this issue even though it is not the perfect solution.
