### ISSUE TITLE
Please remove prefix of class with custom entity

### ISSUE THREAD

**Issue by cvphat4796** [albanian-xrm/Early-Bound#28]
- In dynamics CRM, When we create a custom entity, it will create a schema name with prefix. I will remove it. Both entity and field.

**Comment by BetimBeja** [comment]
Hello @phat471996 ,
do you want an option to remove the publisher prefix from the entity name and the property names for attributes and relationships? Should it update enums generated for optionsets too? How do you suggest we should handle conflicts, if i have a custom attribute bb_Name and out of the box Name, which one should remain?

Best regards,
Betim.

**Comment by cvphat4796** [comment]
Hi @BetimBeja,
Yes I want to remove the publisher prefix and it also should be updated for optionsets.
Currently, I see your project using schema name for Class names, Property names, It is unique.
If you have a custom attribute "bb_Name" and entity "Name". I think you should add a number as surfix. 

Thanks!
Phat

**Comment by cvphat4796** [comment]
With latest release. I have 1 entity "abc_quantity", 1 attribute "abc_quantity". I see you have handled with property in class into "abc_quantity1". So why don't we remove "abc_" ?

**Comment by BetimBeja** [comment]
Hello @cvphat4796,
this feature has been implemented with release v1.2019.10.1

Best regards,
Betim.
