### ISSUE TITLE
Select all for metadata

### ISSUE THREAD

**Issue by andreaPorini** [albanian-xrm/Early-Bound#29]
Hi @BetimBeja 

I'd like to select all the entities/workflow before the generation, how can i do that?

Best regards,
Andrea

**Comment by BetimBeja** [comment]
Hello @andreaPorini,
I haven't implemented a select all functionality... I was obsessed with lowering the assembly size and select all didn't make sense to me, but if you think it might be useful to have such functionality I might implement it.
Best regards,
Betim.

**Comment by andreaPorini** [comment]
Hi @BetimBeja,

I think that a "Select All" functionality could be useful. 

Lowering the size of the file is crucial but, sometimes, I have to include into the Early Bound file a lot of entities and a "Select All" option could help reducing the time "lost" selecting the entities one by one.

Best regards,
Andrea

**Comment by BetimBeja** [comment]
Hello @andreaPorini,
the requested enhancement has been implemented in version v1.2020.3.2

Best regards,
Betim Beja.
