### ISSUE TITLE
Issue generating early bound class with a custom entity

### ISSUE THREAD

**Issue by ssack** [albanian-xrm/Early-Bound#39]
![Annotation 2020-09-03 084842](https://user-images.githubusercontent.com/49202182/92116789-4c6ef580-edc2-11ea-9f8d-97e4192d03a8.png)

Receive this error when selecting a custom entity to generate an early bound class

Thank You for your help
Sal

**Comment by BetimBeja** [comment]
Hello @ssack ,
what is your XrmToolBox version and what authentication type are you using to connect to your organization?

Best regards,
Betim Beja.
