### ISSUE TITLE
Generation error with Auth != from Username & PWD

### ISSUE THREAD

**Issue by Andrea-Bosca** [albanian-xrm/Early-Bound#40]
Hi everyone,

I have an issue generating the Early Bound class when auth differs from Username&Password connection type.

The issue is this one:
![image](https://user-images.githubusercontent.com/72509459/102903406-97e00900-4470-11eb-9e0f-485ff0ef8565.png)
![image](https://user-images.githubusercontent.com/72509459/102903580-d4136980-4470-11eb-9794-8e8250149d52.png)

Best regards,
Andrea

**Comment by BetimBeja** [comment]
Hi @Andrea-Bosca ,
it looks like this is the missing information from issue #39... I have to add better support for the authentication methods supported by CrmSvcUtil.exe

will keep you updated when a fix is ready.
Thank you! Betim Beja.

**Comment by BetimBeja** [comment]
Hello @Andrea-Bosca ,
I released a fix for this right now... can you test if it is ok for you? I tested it with ClientCredentials flow.

**Comment by Andrea-Bosca** [comment]
Hello @BetimBeja ,

now it's working correctly, thank you!

Best regards,
Andrea
